/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/


package euler



object Euler045 {

    def h(n: Long) = n * (2 * n - 1)
    def isPentagonal(n: Long) = ((math.sqrt(1 + 24 * n) + 1.0) / 6.0) % 1 == 0


    def main(args: Array[String]) {
        println((286 to 100000).map(_.toLong).find(n => isPentagonal(h(n))).map(h))

    }

}
